version: "3"
services:
  mysql:
    container_name: guide_db
    image: mysql:8
    volumes:
      - ./docker/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3309:3309"
    expose:
      - 3309
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: aitguide
      MYSQL_TCP_PORT: 3309

  neo4j:
    container_name: guide_neo4j
    image: neo4j:5.17.0
    restart: always
    ports:
      - 57474:7474
      - 7687:7687
    volumes:
      - ./docker/neo4j/volumes/data:/data
      - ./docker/neo4j/volumes/logs:/logs
      - ./docker/neo4j/volumes/conf:/conf
      - ./data:/import
      - ./docker/neo4j/volumes/script:/script
    environment:
      - NEO4J_AUTH=neo4j/madeintokyo
      - EXTENSION_SCRIPT=/script/import_data.sh
    depends_on:
      - "mysql"

  api:
      container_name: guide_api
      image: golang:1.21.6
      stdin_open: true
      tty: true
      volumes:
        - ./src:/root/src
        - ./data:/root/data
      ports:
        - 8080:8080
      depends_on:
        - "neo4j"